obs-ffmpeg: fix build with FFMPEG 8 and above
With commit https://github.com/FFmpeg/FFmpeg/commit/822432769868 FFMPEG
has removed almost all of the FF_API_FF_PROFILE_LEVEL related defines.
They were deprecated since 2023-09-06. This results in build failures
such as:

/var/tmp/portage/media-video/obs-studio-31.1.2/work/obs-studio-31.1.2/plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:279:33: error: ‘FF_PROFILE_HEVC_MAIN’ undeclared (first use in this function); did you mean ‘AV_PROFILE_HEVC_MAIN’?
  279 |                 if ((profile == FF_PROFILE_HEVC_MAIN) && (info.format == VIDEO_FORMAT_P010)) {
      |                                 ^~~~~~~~~~~~~~~~~~~~
      |                                 AV_PROFILE_HEVC_MAIN

This is first found on Gentoo with FFMPEG pre-release version.

Downstream-bug: https://bugs.gentoo.org/961699
Signed-off-by: Brahmajit Das <listout@listout.xyz>